// To do actions
export const ADD_TODO = 'ADD_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const RESET_EDIT_TODO = 'RESET_EDIT_TODO'

// Fridge actions
export const ADD_FRIDGE_ITEM = 'ADD_FRIDGE_ITEM'
export const UPDATE_FRIDGE_ITEM = 'UPDATE_FRIDGE_ITEM'
export const DELETE_FRIDGE_ITEM = 'DELETE_FRIDGE_ITEM'
export const EDIT_FRIDGE_ITEM = 'EDIT_FRIDGE_ITEM'
export const RESET_EDIT_FRIDGE = 'RESET_EDIT_FRIDGE'

// Spendings
export const UPDATE_SPENDINGS = 'UPDATE_TODO'
export const DELETE_SPENDINGS = 'DELETE_TODO'
export const RESET_EDIT_SPENDINGS = 'RESET_EDIT_SPENDINGS'

// Exams
export const ADD_EXAM = 'ADD_EXAM'
export const UPDATE_EXAM = 'UPDATE_EXAM'
export const DELETE_EXAM = 'DELETE_EXAM'
export const TOGGLE_EXAM = 'TOGGLE_EXAM'
export const EDIT_EXAM = 'EDIT_EXAM'
export const RESET_EDIT_EXAM = 'RESET_EDIT_EXAM'

// Shopping list
export const ADD_SHOPPING_ITEM = 'ADD_SHOPPING_ITEM'
export const UPDATE_SHOPPING_ITEM = 'UPDATE_SHOPPING_ITEM'
export const DELETE_SHOPPING_ITEM = 'DELETE_SHOPPING_ITEM'
export const EDIT_SHOPPING_ITEM = 'EDIT_SHOPPING_ITEM'
export const RESET_EDIT_SHOPPING = 'RESET_EDIT_SHOPPING'