// View actions
export const CHANGE_VIEW = 'CHANGE_VIEW'

// To do actions
export const ADD_TODO = 'ADD_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const RESET_EDIT_TODO = 'RESET_EDIT_TODO'
export const SHOW_ALL_TODOS = 'SHOW_ALL_TODOS'
export const SHOW_HIGH_PRIORITY_TODOS = 'SHOW_HIGH_PRIORITY_TODOS'
export const SHOW_LOW_PRIORITY_TODOS = 'SHOW_LOW_PRIORITY_TODOS'

// Fridge actions
export const ADD_FRIDGE_ITEM = 'ADD_FRIDGE_ITEM'
export const UPDATE_FRIDGE_ITEM = 'UPDATE_FRIDGE_ITEM'
export const DELETE_FRIDGE_ITEM = 'DELETE_FRIDGE_ITEM'
export const EDIT_FRIDGE_ITEM = 'EDIT_FRIDGE_ITEM'
export const RESET_EDIT_FRIDGE = 'RESET_EDIT_FRIDGE'

// Spendings
export const UPDATE_SPENDINGS = 'UPDATE_SPENDINGS'
export const DELETE_SPENDINGS = 'DELETE_SPENDINGS'
export const RESET_EDIT_SPENDINGS = 'RESET_EDIT_SPENDINGS'
export const SUBTRACT_SPENDINGS = 'SUBTRACT_SPENDINGS'

// Exams actions
export const ADD_EXAM = 'ADD_EXAM'
export const UPDATE_EXAM = 'UPDATE_EXAM'
export const DELETE_EXAM = 'DELETE_EXAM'
export const TOGGLE_EXAM = 'TOGGLE_EXAM'
export const EDIT_EXAM = 'EDIT_EXAM'
export const RESET_EDIT_EXAM = 'RESET_EDIT_EXAM'
export const SHOW_ALL_EXAMS = 'SHOW_ALL_EXAMS'
export const SHOW_HIGH_PRIORITY_EXAMS = 'SHOW_HIGH_PRIORITY_EXAMS'
export const SHOW_LOW_PRIORITY_EXAMS = 'SHOW_LOW_PRIORITY_EXAMS'

// Shopping list actions
export const ADD_SHOPPING_ITEM = 'ADD_SHOPPING_ITEM'
export const UPDATE_SHOPPING_ITEM = 'UPDATE_SHOPPING_ITEM'
export const DELETE_SHOPPING_ITEM = 'DELETE_SHOPPING_ITEM'
export const EDIT_SHOPPING_ITEM = 'EDIT_SHOPPING_ITEM'
export const RESET_EDIT_SHOPPING = 'RESET_EDIT_SHOPPING'
export const SUBTRACT_COST = 'SUBTRACT_COST'